name: videoModel
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - matplotlib
  - ipykernel
  - scikit-learn
  - hydra-core
  - omegaconf
  - scikit-image
  - pillow
  - ruff
  - pytest
  - beartype
  - ffmpeg
